[package]
name = "yume"
version = "0.1.0"
authors = ["Davy Duperron <yamafaktory@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
async-std = "1.2.0"
base64 = "0.11.0"
futures = "0.3.1"
ring = "0.16.9"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.44"
tui = "0.7.0"
